/**
 * src/modules/audit/ruleConfiguration/questionTypes.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Sprint 6.1 — Rule Configuration Engine: Shared Types & Enums
 *
 * ROLE:
 *   Single source of truth for every type, enum, and interface used across
 *   the entire AI 5S Analysis Pipeline V3.
 *
 * USAGE:
 *   Every pipeline module must import from this file — never redeclare types.
 *   The public API (ruleConfiguration/index.ts) re-exports relevant subsets.
 *
 * PROHIBITIONS:
 *   This file must contain ONLY type definitions.
 *   No runtime logic. No imports from Gemini or pipeline modules.
 */

import type { EvidenceKey } from './evidenceVocabulary';

// ── Pillar keys ───────────────────────────────────────────────────────────────

export type AuditPillarKey =
  | 'SORT'
  | 'SET_IN_ORDER'
  | 'SHINE'
  | 'STANDARDIZE'
  | 'SUSTAIN';

// ── Shared Enums ──────────────────────────────────────────────────────────────

/** Visibility of evidence in the captured image. NOT a compliance indicator. */
export type VisibilityStatusEnum = 'VISIBLE' | 'PARTIALLY_VISIBLE' | 'NOT_VISIBLE';

/** AI audit rating levels (owned by the application, never generated by Gemini). */
export type RatingEnum = 'VERY_GOOD' | 'GOOD' | 'AVERAGE' | 'BAD' | 'VERY_BAD';

/** Pipeline flow control decisions. */
export type PipelineDecisionEnum =
  | 'PASS'
  | 'FAIL'
  | 'STOP_PIPELINE'
  | 'PASS_TO_RULE_ENGINE'
  | 'PASS_TO_OBSERVATION_VALIDATOR'
  | 'PASS_TO_VISIBILITY_ENGINE'
  | 'PASS_TO_STANDARDIZED_EVIDENCE_ENGINE'
  | 'EXCLUDE_FROM_SCORING';

/** Whether a question is active in the current audit template. */
export type QuestionStatusEnum = 'ENABLED' | 'DISABLED';

// ── Uncertainty Response ──────────────────────────────────────────────────────

/** Default response when a question cannot be assessed from the image. */
export interface UncertaintyResponse {
  /** Visibility status to apply when evidence is insufficient. */
  visibility: VisibilityStatusEnum;
  /** Optional human-readable reason for the uncertainty. */
  reason?: string;
}

// ── Observation Guidance ──────────────────────────────────────────────────────

/** Per-question guidance consumed by the Observation Engine and Visibility Engine. */
export interface AuditQuestionGuidance {
  /** What to look for — visible evidence the engine should match. */
  evaluate: string[];
  /** What to ignore — items that should NOT influence the observation. */
  ignore:   string[];
  /** Optional contextual notes for ambiguous situations. */
  notes?:   string[];
  /** Default response when the question cannot be assessed. */
  uncertaintyResponse: UncertaintyResponse;
}

// ── Evidence Configuration ────────────────────────────────────────────────────

/**
 * Defines what evidence the Rule Engine should look for per question.
 * All keys come from the shared EvidenceVocabulary.
 */
export interface EvidenceConfiguration {
  /**
   * Evidence that must be evaluated for this question.
   * The Rule Engine matches detected objects against these keys.
   */
  required:  EvidenceKey[];
  /**
   * Additional evidence that may be relevant but is not mandatory.
   * Optional matches may influence confidence but not the primary rating.
   */
  optional:  EvidenceKey[];
  /**
   * Evidence that should be explicitly excluded from this question's evaluation.
   * If these objects are detected, they must not count as relevant evidence.
   */
  forbidden: EvidenceKey[];
}

// ── Scoring Configuration ─────────────────────────────────────────────────────

/**
 * Threshold for a single rating level.
 * `matchedEvidence` is the count of matched required evidence keys at which
 * this rating applies. Interpretation (presence-is-good vs absence-is-good)
 * is determined by the Rule Engine in Sprint 6.2.
 */
export interface RatingThreshold {
  matchedEvidence: number;
}

/**
 * Complete scoring thresholds for one audit question.
 * All 5 levels must be defined. The Rule Engine uses these to map
 * matched evidence counts to ratings deterministically.
 */
export interface ScoringThresholds {
  veryGood: RatingThreshold;
  good:     RatingThreshold;
  average:  RatingThreshold;
  bad:      RatingThreshold;
  veryBad:  RatingThreshold;
}

export interface ScoringConfiguration {
  thresholds: ScoringThresholds;
}

// ── Question Metadata ─────────────────────────────────────────────────────────

/** Per-question metadata for versioning, tagging, and enabling/disabling. */
export interface QuestionMetadata {
  /** Semantic version of this question definition, e.g. "1.0". */
  version: string;
  /**
   * Whether this question is active in the current audit.
   * Disabled questions are loaded but excluded from scoring.
   */
  enabled: boolean;
  /** Searchable tags for categorisation and filtering. */
  tags:    string[];
}

// ── Enriched Question ─────────────────────────────────────────────────────────

/**
 * A fully enriched audit question containing all configuration needed
 * by every deterministic engine in the pipeline.
 *
 * The Rule Engine should NEVER need question-specific hardcoded logic.
 * Everything required for evaluation is contained in this object.
 */
export interface EnrichedAuditQuestion {
  /** Unique question identifier, e.g. "SORT_Q1". */
  id:       string;
  /** The 5S pillar this question belongs to. */
  pillar:   AuditPillarKey;
  /** The full audit question text — unchanged from the original questions.ts. */
  question: string;
  /** Observation guidance consumed by Sprints 3, 4, and 5. */
  guidance: AuditQuestionGuidance;
  /** Evidence configuration consumed by the Rule Engine (Sprint 6.2). */
  evidence: EvidenceConfiguration;
  /** Scoring configuration consumed by the Question Score Calculator. */
  scoring:  ScoringConfiguration;
  /** Metadata for versioning, filtering, and audit template management. */
  metadata: QuestionMetadata;
}

// ── Audit Configuration Metadata ─────────────────────────────────────────────

/** Global metadata for the complete audit configuration. */
export interface AuditConfigMetadata {
  /** Semantic version of this configuration, e.g. "1.0". */
  configurationVersion:     string;
  /** Name of the audit template, e.g. "Industrial_5S". */
  auditTemplate:            string;
  /** Pipeline version this configuration targets, e.g. "V3". */
  supportedPipelineVersion: string;
  /** ISO date string when this configuration was first created. */
  createdDate:              string;
  /** ISO date string of the last modification. */
  lastModified:             string;
  /** Total number of questions across all pillars. */
  totalQuestions:           number;
}

// ── Audit Configuration (Registry Output) ────────────────────────────────────

/**
 * The immutable output of the Audit Registry.
 * This is the ONLY object that future engines should import from the registry.
 *
 * After loading, this object is deep-frozen.
 * No module may modify it at runtime.
 */
export interface AuditConfiguration {
  /** Questions grouped by pillar. Read-only after registry initialisation. */
  readonly questions:     Readonly<Record<AuditPillarKey, ReadonlyArray<EnrichedAuditQuestion>>>;
  /** All questions as a flat ordered array (SORT → SET_IN_ORDER → SHINE → STANDARDIZE → SUSTAIN). */
  readonly allQuestions:  ReadonlyArray<EnrichedAuditQuestion>;
  /** Global audit configuration metadata. */
  readonly metadata:      Readonly<AuditConfigMetadata>;
}

// ── Configuration Validation ──────────────────────────────────────────────────

export interface ConfigurationValidationError {
  questionId: string;   // "GLOBAL" for registry-level errors
  field:      string;
  message:    string;
}

export interface ConfigurationValidationResult {
  valid:   boolean;
  errors:  ConfigurationValidationError[];
  report: {
    configurationVersion:    string;
    questionCount:           number;
    pillarCount:             number;
    enabledQuestions:        number;
    disabledQuestions:       number;
    duplicateIds:            string[];
    missingEvidenceRules:    string[];
    missingThresholds:       string[];
  };
}
