/**
 * src/modules/audit/report/reportAssembler.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Sprint 8 — Report Builder: Report Assembler
 *
 * ROLE:
 *   Declarative assembly of the Final5SAuditReport from pipeline outputs.
 *   Contains ZERO scoring, grading, or recommendation logic.
 */

import type {
  Final5SAuditReport,
  ReportMetadata,
  ReportOverallSummary,
  ReportPillarSummary,
  ReportQuestionResult,
  ReportExecutionInformation,
} from './reportTypes';
import type {
  OverallScore,
  GradeResult,
  PillarScore,
  QuestionScore,
  StandardizedObservation,
  AuditRecommendationResult,
  AuditDebugTrace,
} from '@/types/analysis';

/**
 * Assembles the final audit report section-by-section using the exact configured order.
 */
export function assembleReport(params: {
  auditId:              string;
  overallScore:         OverallScore;
  gradeResult:          GradeResult;
  pillarScores:         PillarScore[];
  questionScores:       QuestionScore[];
  recommendations:      AuditRecommendationResult;
  observations:         StandardizedObservation[];
  trace:                AuditDebugTrace;
  config:               any;
  executionDuration:    number;
}): Final5SAuditReport {
  const now = new Date();
  const generatedTimestamp = now.toISOString();
  const auditDate = now.toISOString().split('T')[0];

  // Map speedups
  const questionConfigMap = new Map<string, any>();
  if (params.config && Array.isArray(params.config.allQuestions)) {
    for (const q of params.config.allQuestions) {
      questionConfigMap.set(q.id, q);
    }
  }

  const obsMap = new Map<string, StandardizedObservation>();
  for (const obs of params.observations) {
    obsMap.set(obs.questionId, obs);
  }

  const recMap = new Map<string, string>();
  for (const qRec of params.recommendations.questionRecommendations) {
    recMap.set(qRec.questionId, qRec.action);
  }

  // ── 1. Metadata ────────────────────────────────────────────────────────────
  const metadata: ReportMetadata = {
    auditId:              params.auditId,
    auditDate,
    pipelineVersion:      params.config?.metadata?.supportedPipelineVersion ?? 'V3',
    configurationVersion: params.config?.metadata?.configurationVersion     ?? '1.0',
    auditTemplate:        params.config?.metadata?.auditTemplate            ?? 'Industrial_5S',
    executionTime:        params.executionDuration,
    reportVersion:        '1.0',
    generatedTimestamp,
  };

  // ── 2. Overall Summary ──────────────────────────────────────────────────────
  const summary: ReportOverallSummary = {
    overallPercentage:  params.overallScore.percentage,
    grade:              params.gradeResult.grade,
    actualScore:        params.overallScore.actualScore,
    maximumScore:       params.overallScore.maximumScore,
    questionsEvaluated: params.overallScore.evaluatedQuestions,
    skippedQuestions:   params.overallScore.skippedQuestions,
  };

  // ── 3. Pillars ─────────────────────────────────────────────────────────────
  const pillars: ReportPillarSummary[] = params.pillarScores.map(p => ({
    pillar:       p.pillar,
    actualScore:  p.actualScore,
    maximumScore: p.maximumScore,
    percentage:   p.percentage,
  }));

  // ── 4. Questions ───────────────────────────────────────────────────────────
  const questions: ReportQuestionResult[] = params.questionScores.map(q => {
    const configQ = questionConfigMap.get(q.questionId);
    const obs     = obsMap.get(q.questionId);
    const recText = recMap.get(q.questionId);

    return {
      questionId:      q.questionId,
      question:        configQ?.question ?? 'Question text unavailable.',
      visibility:      q.visibility,
      rating:          q.rating,
      score:           q.score,
      maxScore:        q.maxScore,
      scoreEligible:   q.scoreEligible,
      evidenceSummary: obs?.evidence ?? [],
      ...(recText ? { recommendation: recText } : {}),
    };
  });

  // ── 5. Recommendations ─────────────────────────────────────────────────────
  // Preserved exactly as generated by Sprint 7 Recommendation Generator
  const recommendations: AuditRecommendationResult = {
    questionRecommendations: params.recommendations.questionRecommendations.map(r => ({ ...r })),
    pillarRecommendations:   params.recommendations.pillarRecommendations.map(r => ({ ...r })),
    overallRecommendation:   { ...params.recommendations.overallRecommendation },
  };

  // ── 6. Statistics ──────────────────────────────────────────────────────────
  const statistics = {
    eligibleQuestions: params.overallScore.evaluatedQuestions,
    skippedQuestions:  params.overallScore.skippedQuestions,
    evaluatedPillars:   params.overallScore.evaluatedPillars,
    maximumScore:      params.overallScore.maximumScore,
    actualScore:       params.overallScore.actualScore,
  };

  // ── 7. Execution Information ───────────────────────────────────────────────
  const execution: ReportExecutionInformation = {
    pipelineVersion:      params.config?.metadata?.supportedPipelineVersion ?? 'V3',
    configurationVersion: params.config?.metadata?.configurationVersion     ?? '1.0',
    executionDuration:    params.executionDuration,
    auditTraceReference:  params.trace.auditId,
  };

  return {
    metadata,
    summary,
    pillars,
    questions,
    recommendations,
    statistics,
    execution,
  };
}
